---
title: David Hall Notes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: davidsmonkeys@hotmail.com
description: A collection of notes for me. If comprehensible and useful to others, great.
baseurl: notes.davidhall.works
url: http://notes.davidhall.works
github_username: davidsmonkeys
theme: minima
plugins:
- jekyll-feed
